<?php
/*
 $ this file is generated by configure file tool.
 $ warnning: do not modify by manual.
 $ last update at 2013-02-05 14:41:55. 
*/

return array (
  'dbs' => 
  array (
    'default' => 
    array (
      'type' => 'mysql',
      'host' => 'localhost',
      'user' => 'root',
      'pwd' => '',
      'dbname' => 'wayixia',
      'lang' => '',
      'prefix' => 'ch_',
    ),
  ),
  'site' => 
  array (
    'superuid' => '',
    'category_static' => false,
    'name' => 'qlibs',
    'index' => 'index',
    'images_dir' => '/ii',
    'thumb_images_dir' => '/ii/thumb',
    'avatar' => '/avatar',
    'front_cover_dir'=> '/ii/frontcover',
  ),
  'openapi' => 
  array(
    'sinaweibo' => 
      array(
        'WB_AKEY'=>'59191755', 
        'WB_SKEY'=> '143ffeb9cb1838b0b4ac57e52881021d', 'callback'=>'http://wayixia.com/index.php?app=wayixia&mod=openapi&action=sinaweibo'
      ),

    'qq' => 
      array(
        'appid' => '100442004',
        "appkey" =>"01ed21a09044c79e3717c16a4ffed897",
        "callback"=>"http://wayixia.com/index.php?app=wayixia&mod=openapi&action=qq",
        "scope"=>"get_user_info,get_info,get_other_info,add_share,list_album,add_album,upload_pic,add_topic,add_one_blog,add_weibo,check_page_fans,add_t,add_pic_t,del_t,get_repost_list,get_fanslist,get_idolist,add_idol,del_idol,get_tenpay_addr",
      ),
  ),

	'resource' => 
	array(
		'static_domain' => 'http://static.wayixia.com',
		'images_domain' => 'http://img1.s1.wayixia.com',
	),

  'water' => 
  array (
    'enable' => true,
    'width' => 23,
    'height' => 23,
    'text' => 'http://qlibs.com',
    'textsize' => 13,
    'color' => '#FF0000',
    'position' => 9,
  ),
  'upload' => 
  array (
    'dir' => '/upload',
    'images' => '/image',
    'attachments' => '/attach',
    'filters' => 'jpg,jpeg,gif,png,rar,zip,doc,xls',
  ),
  'email' =>
  array (
    'smtpserver' => 'smtp.exmail.qq.com',
    'auth' => 1,
    'user' => 'no-reply@wayixia.com',
    'pwd' => '32A58339194C0E6FX67219',
    'from' => '[挖一下]<no-reply@wayixia.com>',
  ),
  
);

?>
