<?php

/*
 $ file name: includes.required.php
 $ this file is generated by command tool.
 $ if you will add extra php files to impliment some funcitons 
 $ by yourself code, you can add a item into the return array just use relative
 $ path of the app root
*/

return array(
  _KROOT.'/database.class.php',    // for database
  _KROOT.'/page.class.php',
  _KROOT.'/simpleimage.class.php',
  _KROOT.'/qimage.class.php',
  _KROOT.'/q-rpc.php',
  _KROOT.'/smtp.class.php',
  '/rc4crypt.class.php',
  '/function.php',
);

?>
