<?php

/*
 $ file name: includes.required.php
 $ this file is generated by command tool.
 $ if you will add extra php files to impliment some funcitons 
 $ by yourself code, you can add a item into the return array just use relative
 $ path of the app root
*/

return array(
  _QROOT.'/database.class.php', 
  //_QROOT.'/page.class.php',
  _QROOT.'/simpleimage.class.php',
  _QROOT.'/qimage.class.php',
  _QROOT.'/q-rpc.php',
  _QROOT.'/smtp.class.php',
  '/rc4crypt.class.php',
  '/pins.model.php',
  '/function.php',
);

?>
