<?php

/* 
 $ this file is generated by command tool.
 $ it‘s a common app config template.
 $ the 'dbs' section is required. 
*/

$__app_cfgss = array();

/* 数据库 { */

$_app_cfgs['dbs'] = array(
   'default' => 
    array (
      'type' => 'mysql',
      'host' => 'localhost',
      'user' => 'root',
      'pwd' => '',
      'dbname' => 'cdmusic',
      'lang' => 'utf8',
      'prefix' => 'ch_',
    ),
);

/* } */


/* 网站 SITE { */

$_app_cfgs['SITE'] = array();

// 系统超级管理员
// 拥有最高权限
$_app_cfgs['SITE']['CUID'] = '';

// 是否静态调用栏目（需要在后台静态生成栏目）， 默认为动态
$_app_cfgs['SITE']['CATEGORY_HTML']   = false;

// 默认html文件扩展名
$_app_cfgs['SITE']['HTMLEXT'] = '';

// 网站地址
// 网站根地址
$_app_cfgs['SITE']['URL'] = 'http://localhost';

// 网站名称
// 网站的名字
$_app_cfgs['SITE']['NAME'] = 'HOECHEY';

// 首页地址的名称
$_app_cfgs['SITE']['INDEXNAME'] = 'Home';

$_app_cfgs['SITE']['VFCODE'] = '';

/* } */

/* 水印部分 WATER { */

$_app_cfgs['WATER'] = array();

// 是否启用水印功能
// 开启之后，上传的图片将自动添加水印
$_app_cfgs['WATER']['ENABLED'] = '1';

// 图片大小(宽)
// 设置为0为不限
$_app_cfgs['WATER']['WIDTH'] = '23';

// 图片大小(高)
// 
$_app_cfgs['WATER']['HEIGHT'] = '23';

// 文字
// 添加文字水印
$_app_cfgs['WATER']['TEXT'] = 'http://onlyaa.com';

// 文字大小
// 水印文字的大小
$_app_cfgs['WATER']['TEXT_SIZE'] = '13';

// 文字颜色
// 水印文字的颜色
$_app_cfgs['WATER']['TEXT_COLOR'] = '#FF0000';

// 水印位置
// 根据选择将水印加入的相应的位置
$_app_cfgs['WATER']['POSITION'] = '9';

/* } */

/* 上传设置 UPLOAD { */
$_app_cfgs['UPLOAD'] = array();

// 上传文件主目录
$_app_cfgs['UPLOAD']['DIR'] = '/upload';

// 图片上传路径
$_app_cfgs['UPLOAD']['IMAGES'] = '/image';

// 附件上传目录
$_app_cfgs['UPLOAD']['ATTACH'] = '/attach';

// 允许上传的文件类型
$_app_cfgs['UPLOAD']['FILTERS'] = 'jpg,jpeg,gif,png,rar,zip,doc,xls';

/* } */

/* 自定义字段 USER_ { */

/* } */

$_app_cfgs['DEFAULT'] = array(
	/*模板类默认参数*/
	'templates' => array(
                'fileext' => '.html',
    			'tpllist' => 'tpllist',
                'tpllistrule'=> 'list-{cid}-{id}',
    			'tplarticle' => 'tplarticle',
                'tplarticlerule' => 'article-{cid}-{id}',
                'tplindex' => 'tplindex',
                ),
	'images' => array(
                'nopic'=> 'no-pic.gif',
                
    )
);

return $_app_cfgs;

?>
