<?php/*
 $ file name: includes.required.php
 $ this file is generated by command tool.
 $ if you will add extra php files to impliment some funcitons 
 $ by yourself code, you can add a item into the return array just use relative
 $ path of the app root
*/


return array(
//  '/include/function.inc.php',    // yourself php file
	_KROOT.'/database.class.php',
	_KROOT.'/page.class.php'
);

?>
