<?php
/*
 $ this file is generated by configure file tool.
 $ warnning: do not modify by manual.
 $ last update at 2013-06-24 23:45:06. 
*/

return array (
  'dbs' => 
  array (
    'default' => 
    array (
      'type' => 'mysql',
      'host' => 'localhost',
      'user' => 'root',
      'pwd' => '',
      'dbname' => 'collector',
      'lang' => '',
      'prefix' => 'ch_',
    ),
  ),
  'site' => 
  array (
    'superuid' => '',
    'category_static' => false,
    'name' => 'qlibs',
    'index' => 'index',
  ),
  'water' => 
  array (
    'enable' => true,
    'width' => 23,
    'height' => 23,
    'text' => 'http://qlibs.com',
    'textsize' => 13,
    'color' => '#FF0000',
    'position' => 9,
  ),
  'upload' => 
  array (
    'dir' => '/upload',
    'images' => '/image',
    'attachments' => '/attach',
    'filters' => 'jpg,jpeg,gif,png,rar,zip,doc,xls',
  ),
);

?>